name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --user yt-dlp
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Verify yt-dlp installation
        run: yt-dlp --version
      
      - name: Install dependencies
        run: npm install --no-audit --no-fund
      
      - name: Build
        run: npm run build
      
      - name: Run tests
        run: npm test
      
      - name: Test Summary
        if: always()
        run: |
          echo "## Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "Node version: ${{ matrix.node }}" >> $GITHUB_STEP_SUMMARY
          echo "Test file: tests/test.js" >> $GITHUB_STEP_SUMMARY
          echo "Total tests: 8 essential tests" >> $GITHUB_STEP_SUMMARY
      
      # Test artifacts upload removed - no longer needed for simple test suite
